# Generated by Django 4.1.7 on 2023-05-02 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='general',
            new_name='Note',
        ),
    ]
