# Generated by Django 4.1.7 on 2023-05-04 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_note_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='user',
        ),
    ]
